name: terraform hemanth
on:
 push:
  branches: 
   - main
permissions:
 contents: read
jobs:
  plan:
   runs-on: ubuntu-22.04
   steps:
   - name: checkout
     uses: actions/checkout@v4
   - name: set up terraform
     uses: hashicorp/setup-terraform@v3
   - name: fmt check
     run: terraform fmt -check -recursive
     continue-on-error: true
   - name: init
     run: terraform init
   - name: validate
     run: terraform validate
   - name: terraform plan
     run: terraform plan -out=tf.plan
   - name: upload plan
     uses: actions/upload-artifact@v4
     with:
       path: tf.plan
   - name: apply
     run: terraform apply tf.plan
       
     
